2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_setup.py:_flush():76] Configure stats pid to 2614
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from /home/codespace/.config/wandb/settings
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'raihaan123', 'project': 'PINNs', 'root_dir': '/workspaces/UROP-Notes', 'run_id': 'jg63lx97', 'sweep_param_path': '/workspaces/UROP-Notes/wandb/sweep-jy42uwvz/config-jg63lx97.yaml', 'sweep_id': 'jy42uwvz'}
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/runner.py', 'program': '/workspaces/UROP-Notes/src/runner.py'}
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_init.py:_log_setup():461] Logging user logs to /workspaces/UROP-Notes/wandb/run-20220821_223845-jg63lx97/logs/debug.log
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_init.py:_log_setup():462] Logging internal logs to /workspaces/UROP-Notes/wandb/run-20220821_223845-jg63lx97/logs/debug-internal.log
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():495] calling init triggers
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():498] wandb.init called with sweep_config: {'depth': 12, 'height': 100, 'num_domain': 900}
config: {}
2022-08-21 22:38:45,686 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():548] starting backend
2022-08-21 22:38:45,687 INFO    Thread-12 (_run_job):2614 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-21 22:38:45,692 INFO    Thread-12 (_run_job):2614 [backend.py:ensure_launched():217] starting backend process...
2022-08-21 22:38:45,692 INFO    Thread-12 (_run_job):2614 [backend.py:ensure_launched():222] started backend process with pid: 4251
2022-08-21 22:38:45,693 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():558] backend started and connected
2022-08-21 22:38:45,699 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_config_callback():1131] config_cb None None {'depth': 12, 'height': 100, 'num_domain': 900}
2022-08-21 22:38:45,701 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():634] updated telemetry
2022-08-21 22:38:45,707 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-21 22:38:46,763 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_init():1919] communicating current version
2022-08-21 22:38:46,801 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-21 22:38:46,801 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():700] starting run threads in backend
2022-08-21 22:38:46,848 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_console_start():1893] atexit reg
2022-08-21 22:38:46,849 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-21 22:38:46,849 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-21 22:38:46,849 ERROR   Thread-12 (_run_job):2614 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/python/3.10.4/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-08-21 22:38:46,850 INFO    Thread-12 (_run_job):2614 [wandb_init.py:init():732] run started, returning control to user process
2022-08-21 22:42:18,606 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_finish():1680] finishing run raihaan123/PINNs/jg63lx97
2022-08-21 22:42:18,614 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-21 22:42:18,615 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_restore():1834] restore
2022-08-21 22:42:18,618 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 680
  total_bytes: 680
}

2022-08-21 22:42:18,825 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 680
  total_bytes: 680
}

2022-08-21 22:42:18,926 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 680
  total_bytes: 3718
}

2022-08-21 22:42:19,028 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1304
  total_bytes: 3718
}

2022-08-21 22:42:19,130 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}

2022-08-21 22:42:19,233 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}

2022-08-21 22:42:19,335 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}

2022-08-21 22:42:19,437 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}

2022-08-21 22:42:19,539 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}

2022-08-21 22:42:20,012 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}

2022-08-21 22:42:20,377 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3718
  total_bytes: 3718
}
local_info {
}

2022-08-21 22:42:21,651 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-21 22:42:21,651 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-21 22:42:21,681 INFO    Thread-12 (_run_job):2614 [wandb_run.py:_footer_sync_info():3055] logging synced files
