2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_setup.py:_flush():76] Configure stats pid to 2614
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from /home/codespace/.config/wandb/settings
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'raihaan123', 'project': 'PINNs', 'root_dir': '/workspaces/UROP-Notes', 'run_id': 'v8dce38u', 'sweep_param_path': '/workspaces/UROP-Notes/wandb/sweep-jy42uwvz/config-v8dce38u.yaml', 'sweep_id': 'jy42uwvz'}
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/runner.py', 'program': '/workspaces/UROP-Notes/src/runner.py'}
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_init.py:_log_setup():461] Logging user logs to /workspaces/UROP-Notes/wandb/run-20220821_224223-v8dce38u/logs/debug.log
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_init.py:_log_setup():462] Logging internal logs to /workspaces/UROP-Notes/wandb/run-20220821_224223-v8dce38u/logs/debug-internal.log
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():495] calling init triggers
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():498] wandb.init called with sweep_config: {'depth': 41, 'height': 12, 'num_domain': 600}
config: {}
2022-08-21 22:42:23,724 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():548] starting backend
2022-08-21 22:42:23,725 INFO    Thread-17 (_run_job):2614 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-21 22:42:23,729 INFO    Thread-17 (_run_job):2614 [backend.py:ensure_launched():217] starting backend process...
2022-08-21 22:42:23,759 INFO    Thread-17 (_run_job):2614 [backend.py:ensure_launched():222] started backend process with pid: 5228
2022-08-21 22:42:23,759 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():558] backend started and connected
2022-08-21 22:42:23,766 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_config_callback():1131] config_cb None None {'depth': 41, 'height': 12, 'num_domain': 600}
2022-08-21 22:42:23,768 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():634] updated telemetry
2022-08-21 22:42:23,772 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-21 22:42:31,673 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_init():1919] communicating current version
2022-08-21 22:42:31,743 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-21 22:42:31,744 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():700] starting run threads in backend
2022-08-21 22:42:32,046 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_console_start():1893] atexit reg
2022-08-21 22:42:32,047 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-21 22:42:32,047 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-21 22:42:32,048 ERROR   Thread-17 (_run_job):2614 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/opt/python/3.10.4/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/python/3.10.4/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-08-21 22:42:32,048 INFO    Thread-17 (_run_job):2614 [wandb_init.py:init():732] run started, returning control to user process
2022-08-21 22:42:57,920 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_finish():1680] finishing run raihaan123/PINNs/v8dce38u
2022-08-21 22:42:57,920 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-21 22:42:57,921 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_restore():1834] restore
2022-08-21 22:42:57,932 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 4011
}

2022-08-21 22:42:58,175 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 4011
}

2022-08-21 22:42:58,730 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 7081
}

2022-08-21 22:42:58,832 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 4011
  total_bytes: 7081
}

2022-08-21 22:42:58,935 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 6542
  total_bytes: 7081
}

2022-08-21 22:42:59,037 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:42:59,138 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:42:59,240 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:42:59,343 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:42:59,445 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:43:00,512 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}

2022-08-21 22:43:00,878 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 7081
  total_bytes: 7081
}
local_info {
}

2022-08-21 22:43:02,033 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-21 22:43:02,034 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-21 22:43:02,037 INFO    Thread-17 (_run_job):2614 [wandb_run.py:_footer_sync_info():3055] logging synced files
